server:
  port: 8181

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: usr
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  application:
    name: AR-api
      
ssaWebApiURL: http://aws-public-ip:8080/ssa      
      
    
#  boot:
#    admin:
#      client:
#        url:
#        - http://localhost:8081/
#        
#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#        - '*'               
    
    
